language: php

php:
  - 5.6

install:
  - composer install

script: phpunit --coverage-text

services:
  - postgresql

before_script:
  - psql -c 'create database gonzalo;' -U username
  - psql -c 'create database gonzalo2;' -U username
  - psql -c 'create database gonzalo3;' -U username